### ISSUE TITLE
UI - Add Confirmation to VM Revert

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/TopoMojo#30]
The "Revert" button does not have a confirmation and is close to the "Save" button. This can lead to inadvertently reverting changes that you made to the VM if your click isn't accurate. 

![image](https://github.com/cmu-sei/TopoMojo/assets/89405171/677408a1-c5ef-4080-8be3-8c7144956c7a)

**Comment by sei-jmattson** [comment]
Fixed in v2.3.0
