### ISSUE TITLE
Compete Support for Question Sets

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/TopoMojo#46]
Question Sets currently have a [TODO](https://github.com/cmu-sei/TopoMojo/blob/3cbba18205e61edead1dac4595f031c921882097/src/TopoMojo.Api/Features/Gamespace/GamespaceService.cs#L593) preventing them from fully working as intended.  We should finish that up so we can make use of that feature.

**Comment by sei-bstein** [comment]
Raring to go on this. Will plan to start work 10/1 and submit a PR for review by @sei-jmattson when it's ready.

**Comment by sei-jbooz** [comment]
Resolved with #52
